[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 兜底：把所有非静态请求路由到 Next 服务端函数
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200
